<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130406055131 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Adjunto (id INT AUTO_INCREMENT NOT NULL, oficio_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, INDEX IDX_B701F5AC8D7E696E (oficio_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Comentario (id INT AUTO_INCREMENT NOT NULL, oficio_id INT DEFAULT NULL, comentario VARCHAR(255) NOT NULL, timestamp DATETIME NOT NULL, INDEX IDX_4CCE4D28D7E696E (oficio_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Departamento (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Oficio (id INT AUTO_INCREMENT NOT NULL, emisor_id INT DEFAULT NULL, numero INT NOT NULL, descripcion VARCHAR(255) NOT NULL, recibio VARCHAR(255) NOT NULL, estado VARCHAR(255) DEFAULT NULL, timestamp DATETIME DEFAULT NULL, emitido DATETIME DEFAULT NULL, INDEX IDX_3C33FA206BDF87DF (emisor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE fos_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_957A647992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_957A6479A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Adjunto ADD CONSTRAINT FK_B701F5AC8D7E696E FOREIGN KEY (oficio_id) REFERENCES Oficio (id)");
        $this->addSql("ALTER TABLE Comentario ADD CONSTRAINT FK_4CCE4D28D7E696E FOREIGN KEY (oficio_id) REFERENCES Oficio (id)");
        $this->addSql("ALTER TABLE Oficio ADD CONSTRAINT FK_3C33FA206BDF87DF FOREIGN KEY (emisor_id) REFERENCES Departamento (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Oficio DROP FOREIGN KEY FK_3C33FA206BDF87DF");
        $this->addSql("ALTER TABLE Adjunto DROP FOREIGN KEY FK_B701F5AC8D7E696E");
        $this->addSql("ALTER TABLE Comentario DROP FOREIGN KEY FK_4CCE4D28D7E696E");
        $this->addSql("DROP TABLE Adjunto");
        $this->addSql("DROP TABLE Comentario");
        $this->addSql("DROP TABLE Departamento");
        $this->addSql("DROP TABLE Oficio");
        $this->addSql("DROP TABLE fos_user");
    }
}
