<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130528211022 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE TipoSolicitud (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE comentario ADD finalizado DATETIME DEFAULT NULL, DROP estado, CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE documento ADD tipo_solicitud_id INT DEFAULT NULL, ADD fecha_de_respuesta DATETIME DEFAULT NULL, ADD responder TINYINT(1) NOT NULL, ADD gca TINYINT(1) NOT NULL, DROP estado");
        $this->addSql("ALTER TABLE documento ADD CONSTRAINT FK_3440AC64AFEA88E4 FOREIGN KEY (tipo_solicitud_id) REFERENCES TipoSolicitud (id)");
        $this->addSql("CREATE INDEX IDX_3440AC64AFEA88E4 ON documento (tipo_solicitud_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Documento DROP FOREIGN KEY FK_3440AC64AFEA88E4");
        $this->addSql("DROP TABLE TipoSolicitud");
        $this->addSql("ALTER TABLE Comentario ADD estado VARCHAR(255) NOT NULL, DROP finalizado, CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("DROP INDEX IDX_3440AC64AFEA88E4 ON Documento");
        $this->addSql("ALTER TABLE Documento ADD estado VARCHAR(255) DEFAULT NULL, DROP tipo_solicitud_id, DROP fecha_de_respuesta, DROP responder, DROP gca");
    }
}
