<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130518030518 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Adjunto (id INT AUTO_INCREMENT NOT NULL, documento_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, INDEX IDX_B701F5AC45C0CF75 (documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Comentario (id INT AUTO_INCREMENT NOT NULL, documento_id INT DEFAULT NULL, comentario VARCHAR(255) NOT NULL, timestamp DATETIME NOT NULL, estado VARCHAR(255) NOT NULL, INDEX IDX_4CCE4D245C0CF75 (documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Departamento (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE departamento_documento (departamento_id INT NOT NULL, documento_id INT NOT NULL, INDEX IDX_D94A08495A91C08D (departamento_id), INDEX IDX_D94A084945C0CF75 (documento_id), PRIMARY KEY(departamento_id, documento_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Documento (id INT AUTO_INCREMENT NOT NULL, tipo_documento_id INT DEFAULT NULL, emisor_id INT DEFAULT NULL, numero VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, autor VARCHAR(255) NOT NULL, entregado VARCHAR(255) NOT NULL, destinatario VARCHAR(255) NOT NULL, recibio VARCHAR(255) NOT NULL, fecha_de_emision DATETIME NOT NULL, fecha_de_envio DATETIME NOT NULL, fecha_de_recibido DATETIME NOT NULL, estado VARCHAR(255) DEFAULT NULL, respondido TINYINT(1) NOT NULL, recibido TINYINT(1) NOT NULL, INDEX IDX_3440AC64F6939175 (tipo_documento_id), INDEX IDX_3440AC646BDF87DF (emisor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE enviado_departamento (documento_id INT NOT NULL, departamento_id INT NOT NULL, INDEX IDX_B10478B245C0CF75 (documento_id), INDEX IDX_B10478B25A91C08D (departamento_id), PRIMARY KEY(documento_id, departamento_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE TipoDocumento (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE fos_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_957A647992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_957A6479A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Adjunto ADD CONSTRAINT FK_B701F5AC45C0CF75 FOREIGN KEY (documento_id) REFERENCES Documento (id)");
        $this->addSql("ALTER TABLE Comentario ADD CONSTRAINT FK_4CCE4D245C0CF75 FOREIGN KEY (documento_id) REFERENCES Documento (id)");
        $this->addSql("ALTER TABLE departamento_documento ADD CONSTRAINT FK_D94A08495A91C08D FOREIGN KEY (departamento_id) REFERENCES Departamento (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE departamento_documento ADD CONSTRAINT FK_D94A084945C0CF75 FOREIGN KEY (documento_id) REFERENCES Documento (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Documento ADD CONSTRAINT FK_3440AC64F6939175 FOREIGN KEY (tipo_documento_id) REFERENCES TipoDocumento (id)");
        $this->addSql("ALTER TABLE Documento ADD CONSTRAINT FK_3440AC646BDF87DF FOREIGN KEY (emisor_id) REFERENCES Departamento (id)");
        $this->addSql("ALTER TABLE enviado_departamento ADD CONSTRAINT FK_B10478B245C0CF75 FOREIGN KEY (documento_id) REFERENCES Documento (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE enviado_departamento ADD CONSTRAINT FK_B10478B25A91C08D FOREIGN KEY (departamento_id) REFERENCES Departamento (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE departamento_documento DROP FOREIGN KEY FK_D94A08495A91C08D");
        $this->addSql("ALTER TABLE Documento DROP FOREIGN KEY FK_3440AC646BDF87DF");
        $this->addSql("ALTER TABLE enviado_departamento DROP FOREIGN KEY FK_B10478B25A91C08D");
        $this->addSql("ALTER TABLE Adjunto DROP FOREIGN KEY FK_B701F5AC45C0CF75");
        $this->addSql("ALTER TABLE Comentario DROP FOREIGN KEY FK_4CCE4D245C0CF75");
        $this->addSql("ALTER TABLE departamento_documento DROP FOREIGN KEY FK_D94A084945C0CF75");
        $this->addSql("ALTER TABLE enviado_departamento DROP FOREIGN KEY FK_B10478B245C0CF75");
        $this->addSql("ALTER TABLE Documento DROP FOREIGN KEY FK_3440AC64F6939175");
        $this->addSql("DROP TABLE Adjunto");
        $this->addSql("DROP TABLE Comentario");
        $this->addSql("DROP TABLE Departamento");
        $this->addSql("DROP TABLE departamento_documento");
        $this->addSql("DROP TABLE Documento");
        $this->addSql("DROP TABLE enviado_departamento");
        $this->addSql("DROP TABLE TipoDocumento");
        $this->addSql("DROP TABLE fos_user");
    }
}
