<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130428220219 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE oficio ADD remitente VARCHAR(255) DEFAULT NULL, ADD destinatario VARCHAR(255) DEFAULT NULL, CHANGE timestamp timestamp DATETIME DEFAULT NULL, CHANGE emitido emitido DATETIME DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE Oficio DROP remitente, DROP destinatario, CHANGE timestamp timestamp DATETIME DEFAULT NULL, CHANGE emitido emitido DATETIME DEFAULT NULL");
    }
}
