<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130604040601 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Accion (id INT AUTO_INCREMENT NOT NULL, tipo_accion_id INT DEFAULT NULL, documento_id INT DEFAULT NULL, descripcion VARCHAR(255) NOT NULL, fecha DATETIME NOT NULL, INDEX IDX_8DAEE682DD25ED3B (tipo_accion_id), INDEX IDX_8DAEE68245C0CF75 (documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE TipoAccion (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Accion ADD CONSTRAINT FK_8DAEE682DD25ED3B FOREIGN KEY (tipo_accion_id) REFERENCES TipoAccion (id)");
        $this->addSql("ALTER TABLE Accion ADD CONSTRAINT FK_8DAEE68245C0CF75 FOREIGN KEY (documento_id) REFERENCES Documento (id)");
        $this->addSql("ALTER TABLE comentario CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE documento ADD clasificar TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Accion DROP FOREIGN KEY FK_8DAEE682DD25ED3B");
        $this->addSql("DROP TABLE Accion");
        $this->addSql("DROP TABLE TipoAccion");
        $this->addSql("ALTER TABLE Comentario CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE Documento DROP clasificar");
    }
}
