<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130603030548 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE TipoDepartamento (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE comentario CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE departamento ADD tipo_departamento_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE departamento ADD CONSTRAINT FK_58D54C138CCBB0AA FOREIGN KEY (tipo_departamento_id) REFERENCES TipoDepartamento (id)");
        $this->addSql("CREATE INDEX IDX_58D54C138CCBB0AA ON departamento (tipo_departamento_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Departamento DROP FOREIGN KEY FK_58D54C138CCBB0AA");
        $this->addSql("DROP TABLE TipoDepartamento");
        $this->addSql("ALTER TABLE Comentario CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
        $this->addSql("DROP INDEX IDX_58D54C138CCBB0AA ON Departamento");
        $this->addSql("ALTER TABLE Departamento DROP tipo_departamento_id");
    }
}
