<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130428220619 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE oficio CHANGE numero numero VARCHAR(255) NOT NULL, CHANGE timestamp timestamp DATETIME DEFAULT NULL, CHANGE emitido emitido DATETIME DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE Oficio CHANGE numero numero INT NOT NULL, CHANGE timestamp timestamp DATETIME DEFAULT NULL, CHANGE emitido emitido DATETIME DEFAULT NULL");
    }
}
