<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130605010349 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE accion CHANGE fecha fecha DATETIME NOT NULL");
        $this->addSql("ALTER TABLE comentario ADD editable TINYINT(1) DEFAULT NULL, CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Accion CHANGE fecha fecha DATETIME NOT NULL");
        $this->addSql("ALTER TABLE Comentario DROP editable, CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
    }
}
