<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130526210100 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE departamento ADD color VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE tipodocumento ADD color VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE Departamento DROP color");
        $this->addSql("ALTER TABLE TipoDocumento DROP color");
    }
}
