<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130528224536 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comentario CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE documento CHANGE respondido respondido TINYINT(1) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Comentario CHANGE timestamp timestamp DATETIME NOT NULL, CHANGE finalizado finalizado DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE Documento CHANGE respondido respondido TINYINT(1) NOT NULL");
    }
}
