<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130520212843 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE documento CHANGE descripcion descripcion VARCHAR(255) DEFAULT NULL, CHANGE autor autor VARCHAR(255) DEFAULT NULL, CHANGE destinatario destinatario VARCHAR(255) DEFAULT NULL, CHANGE recibio recibio VARCHAR(255) DEFAULT NULL, CHANGE fecha_de_emision fecha_de_emision DATETIME DEFAULT NULL, CHANGE fecha_de_envio fecha_de_envio DATETIME DEFAULT NULL, CHANGE fecha_de_recibido fecha_de_recibido DATETIME DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Comentario CHANGE timestamp timestamp DATETIME NOT NULL");
        $this->addSql("ALTER TABLE Documento CHANGE descripcion descripcion VARCHAR(255) NOT NULL, CHANGE autor autor VARCHAR(255) NOT NULL, CHANGE destinatario destinatario VARCHAR(255) NOT NULL, CHANGE recibio recibio VARCHAR(255) NOT NULL, CHANGE fecha_de_emision fecha_de_emision DATETIME NOT NULL, CHANGE fecha_de_envio fecha_de_envio DATETIME NOT NULL, CHANGE fecha_de_recibido fecha_de_recibido DATETIME NOT NULL");
    }
}
