UNAHSGOBundle_homepage:
    pattern:  /
    defaults: { _controller: UNAHSGOBundle:Default:index }

UNAHSGOBundle_default:
    pattern:  /home
    defaults: { _controller: UNAHSGOBundle:Default:index }

UNAHSGOBundle_help:
    pattern:  /help
    defaults: { _controller: UNAHSGOBundle:Default:help }

UNAHSGOBundle_clasificar:
    pattern:  /clasificar
    defaults: { _controller: UNAHSGOBundle:Default:clasificar }

UNAHSGOBundle_departamento:
    resource: "@UNAHSGOBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento

UNAHSGOBundle_comentario:
    resource: "@UNAHSGOBundle/Resources/config/routing/comentario.yml"
    prefix:   /comentario

UNAHSGOBundle_adjunto:
    resource: "@UNAHSGOBundle/Resources/config/routing/adjunto.yml"
    prefix:   /adjunto

UNAHSGOBundle_tipodocumento:
    resource: "@UNAHSGOBundle/Resources/config/routing/tipodocumento.yml"
    prefix:   /tipodocumento

UNAHSGOBundle_documento:
    resource: "@UNAHSGOBundle/Resources/config/routing/documento.yml"
    prefix:   /documento

UNAHSGOBundle_tiposolicitud:
    resource: "@UNAHSGOBundle/Resources/config/routing/tiposolicitud.yml"
    prefix:   /tiposolicitud

UNAHSGOBundle_accion:
    resource: "@UNAHSGOBundle/Resources/config/routing/accion.yml"
    prefix:   /accion

UNAHSGOBundle_tipoaccion:
    resource: "@UNAHSGOBundle/Resources/config/routing/tipoaccion.yml"
    prefix:   /tipoaccion

UNAHSGOBundle_coordinacion:
    resource: "@UNAHSGOBundle/Resources/config/routing/coordinacion.yml"
    prefix:   /coordinacion

UNAHSGOBundle_instancia:
    resource: "@UNAHSGOBundle/Resources/config/routing/instancia.yml"
    prefix:   /instancia

UNAHSGOBundle_carrera:
    resource: "@UNAHSGOBundle/Resources/config/routing/carrera.yml"
    prefix:   /carrera

UNAHSGOBundle_facultad:
    resource: "@UNAHSGOBundle/Resources/config/routing/facultad.yml"
    prefix:   /facultad

UNAHSGOBundle_centro:
    resource: "@UNAHSGOBundle/Resources/config/routing/centro.yml"
    prefix:   /centro
