UNAHSGOBundle_homepage:
    pattern:  /
    defaults: { _controller: UNAHSGOBundle:Default:index }

UNAHSGOBundle_default:
    pattern:  /home
    defaults: { _controller: UNAHSGOBundle:Default:index }

UNAHSGOBundle_departamento:
    resource: "@UNAHSGOBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento

UNAHSGOBundle_comentario:
    resource: "@UNAHSGOBundle/Resources/config/routing/comentario.yml"
    prefix:   /comentario

UNAHSGOBundle_adjunto:
    resource: "@UNAHSGOBundle/Resources/config/routing/adjunto.yml"
    prefix:   /adjunto

UNAHSGOBundle_tipodocumento:
    resource: "@UNAHSGOBundle/Resources/config/routing/tipodocumento.yml"
    prefix:   /tipodocumento

UNAHSGOBundle_documento:
    resource: "@UNAHSGOBundle/Resources/config/routing/documento.yml"
    prefix:   /documento

UNAHSGOBundle_tiposolicitud:
    resource: "@UNAHSGOBundle/Resources/config/routing/tiposolicitud.yml"
    prefix:   /tiposolicitud

UNAHSGOBundle_accion:
    resource: "@UNAHSGOBundle/Resources/config/routing/accion.yml"
    prefix:   /accion
