departamento:
    pattern:  /
    defaults: { _controller: "UNAHSGOBundle:Departamento:index" }

departamento_show:
    pattern:  /{id}/show
    defaults: { _controller: "UNAHSGOBundle:Departamento:show" }

departamento_tipo:
    pattern:  /tipo
    defaults: { _controller: "UNAHSGOBundle:Departamento:tipo" }

departamento_new:
    pattern:  /new
    defaults: { _controller: "UNAHSGOBundle:Departamento:new" }

departamento_create:
    pattern:  /create
    defaults: { _controller: "UNAHSGOBundle:Departamento:create" }
    requirements: { _method: post }

departamento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UNAHSGOBundle:Departamento:edit" }

departamento_update:
    pattern:  /{id}/update
    defaults: { _controller: "UNAHSGOBundle:Departamento:update" }
    requirements: { _method: post|put }

departamento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UNAHSGOBundle:Departamento:delete" }
    requirements: { _method: post|delete }
