documento:
    pattern:  /
    defaults: { _controller: "UNAHSGOBundle:Documento:index" }

documento_show:
    pattern:  /{id}/show
    defaults: { _controller: "UNAHSGOBundle:Documento:show" }

documento_new:
    pattern:  /new
    defaults: { _controller: "UNAHSGOBundle:Documento:new" }

documento_create:
    pattern:  /create/{tipo}
    defaults: { _controller: "UNAHSGOBundle:Documento:create" }
    requirements: { _method: post }

documento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UNAHSGOBundle:Documento:edit" }

documento_update:
    pattern:  /{id}/update
    defaults: { _controller: "UNAHSGOBundle:Documento:update" }
    requirements: { _method: post|put }
    
documento_edit_enviado:
    pattern:  /{id}/edit/enviado
    defaults: { _controller: "UNAHSGOBundle:Documento:editEnviado" }

documento_update_enviado:
    pattern:  /{id}/update/enviado
    defaults: { _controller: "UNAHSGOBundle:Documento:updateEnviado" }
    requirements: { _method: post|put }

documento_edit_recibido:
    pattern:  /{id}/edit/recibido
    defaults: { _controller: "UNAHSGOBundle:Documento:editRecibido" }

documento_update_recibido:
    pattern:  /{id}/update/recibido
    defaults: { _controller: "UNAHSGOBundle:Documento:updateRecibido" }
    requirements: { _method: post|put }

documento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UNAHSGOBundle:Documento:delete" }
    requirements: { _method: post|delete }

documento_recibiendo:
    pattern:  /recibiendo/{tipo}
    defaults: { _controller: "UNAHSGOBundle:Documento:recibiendo" }

documento_recibir:
    pattern:  /recibir/{tipo}
    defaults: { _controller: "UNAHSGOBundle:Documento:recibir" }
    requirements: { _method: post }

documento_enviando:
    pattern:  /enviando/{tipo}
    defaults: { _controller: "UNAHSGOBundle:Documento:enviando" }

documento_enviar:
    pattern:  /enviar/{tipo}
    defaults: { _controller: "UNAHSGOBundle:Documento:enviar" }
    requirements: { _method: post }

documento_responder:
    pattern:  /responder/{documento}
    defaults: { _controller: "UNAHSGOBundle:Documento:responder" }

documento_respuesta:
    pattern:  /respuesta/{documento}
    defaults: { _controller: "UNAHSGOBundle:Documento:respuesta" }
    requirements: { _method: post }

documento_search_date:
    pattern: /fecha
    defaults: { _controller: "UNAHSGOBundle:Documento:searchDate" }

documento_search:
    pattern: /buscar
    defaults: { _controller: "UNAHSGOBundle:Documento:search" }

documento_search_emision:
    pattern: /emision
    defaults: { _controller: "UNAHSGOBundle:Documento:searchEmision" }

documento_search_numero:
    pattern: /numero
    defaults: { _controller: "UNAHSGOBundle:Documento:searchNumero" }

documento_search_depto:
    pattern: /dependencia
    defaults: { _controller: "UNAHSGOBundle:Documento:searchDepartamento" }
    
documento_search_depto_comentario:
    pattern: /dependencia/descripcion
    defaults: { _controller: "UNAHSGOBundle:Documento:searchDepartamentoComentario" }

documento_estadistica_periodo:
    pattern: /estadistica/periodo
    defaults: { _controller: "UNAHSGOBundle:Documento:estadisticaPeriodo" }

documento_estadistica_periodo_tipo:
    pattern: /estadistica/periodo/tipo
    defaults: { _controller: "UNAHSGOBundle:Documento:estadisticaPeriodoTipo" }

documento_documento:
    pattern: /documento/{tipo}
    defaults: { _controller: "UNAHSGOBundle:Documento:Tipo" }
