tipoaccion:
    pattern:  /
    defaults: { _controller: "UNAHSGOBundle:TipoAccion:index" }

tipoaccion_show:
    pattern:  /{id}/show
    defaults: { _controller: "UNAHSGOBundle:TipoAccion:show" }

tipoaccion_new:
    pattern:  /new
    defaults: { _controller: "UNAHSGOBundle:TipoAccion:new" }

tipoaccion_create:
    pattern:  /create
    defaults: { _controller: "UNAHSGOBundle:TipoAccion:create" }
    requirements: { _method: post }

tipoaccion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UNAHSGOBundle:TipoAccion:edit" }

tipoaccion_update:
    pattern:  /{id}/update
    defaults: { _controller: "UNAHSGOBundle:TipoAccion:update" }
    requirements: { _method: post|put }

tipoaccion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UNAHSGOBundle:TipoAccion:delete" }
    requirements: { _method: post|delete }
